# Generated by Django 2.2.15 on 2020-08-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_ghfghjgkjhg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='title',
        ),
        migrations.AddField(
            model_name='customtext',
            name='y8',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
